package dadkvs.server.comunications;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsConsole;
import dadkvs.DadkvsConsoleServiceGrpc;
import dadkvs.server.domain.DadkvsServerState;
import io.grpc.stub.StreamObserver;

public class DadkvsConsoleServiceImpl extends DadkvsConsoleServiceGrpc.DadkvsConsoleServiceImplBase {

    DadkvsServerState server_state;

    public DadkvsConsoleServiceImpl(DadkvsServerState state) {
        this.server_state = state;
    }

    @Override
    public void setleader(DadkvsConsole.SetLeaderRequest request, StreamObserver<DadkvsConsole.SetLeaderReply> responseObserver) {
        this.server_state.changeLeaderMode(request.getIsleader());
        this.server_state.getMainLoop().wakeup();

        DadkvsConsole.SetLeaderReply response = DadkvsConsole.SetLeaderReply.newBuilder().setIsleaderack(true).build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void setdebug(DadkvsConsole.SetDebugRequest request, StreamObserver<DadkvsConsole.SetDebugReply> responseObserver) {
        this.server_state.changeDebugMode(request.getMode());
        this.server_state.getMainLoop().wakeup();

        DadkvsConsole.SetDebugReply response = DadkvsConsole.SetDebugReply.newBuilder().setAck(true).build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

}
